# Generated by Django 4.0.4 on 2022-05-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yatch_Main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilenme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Yatch Master',
                'verbose_name_plural': 'Yatch Master',
            },
        ),
        migrations.CreateModel(
            name='Yatch_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='Reservation Date')),
                ('tour_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tour Code')),
                ('customer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer')),
                ('nofplace', models.CharField(blank=True, max_length=50, null=True, verbose_name='From to')),
                ('tour_detail', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tour Details')),
                ('yatch_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Yatch Name')),
                ('guide', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guide')),
                ('operation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilenme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('id_related', models.ForeignKey(help_text='id', on_delete=django.db.models.deletion.CASCADE, to='reservations.yatch_main', verbose_name='id')),
            ],
            options={
                'verbose_name': 'Yatch Reservation',
                'verbose_name_plural': 'Yatch Reservation',
            },
        ),
    ]
