# Generated by Django 4.0.4 on 2022-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatch_reservation',
            name='pax',
            field=models.FloatField(default=0, verbose_name='Pax'),
        ),
    ]
