# Generated by Django 4.0.4 on 2022-05-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_yatch_reservation_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatch_reservation',
            name='tour_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Tour Details'),
        ),
    ]
